### PR TITLE
Added new busy spinner, with cool animation

### PR DESCRIPTION
**Pull request by frodo19**
Merge if you like it.

### CODE REVIEW

**Review by b-jesch — COMMENTED** [review]
This is not my thing, but will make this selectable similar to the pattern types in skin settings...

**Comment by b-jesch** [comment]
Implemented by https://github.com/b-jesch/skin.estuary.modv2/commit/097028872e99404340b98bf2abb65d8fe27fa2de

**Comment by frodo19** [comment]
Thanks :)

**Comment by b-jesch** [comment]
Added a third spinner (not on github yet):

spinner_3

**Pull request closed without merging**
